In [2]:
import numpy as np

In [3]:
np.unique([4,3,3,2])

array([2, 3, 4])

In [4]:
np.unique([4,3,3,2], return_counts=True) # 4 on en a 1, 3 on en a 2 et 2 on en a 1

(array([2, 3, 4]), array([1, 2, 1]))

In [5]:
np.unique([4,3,3,2], return_inverse=True) # affiche une seule fois les valeurs, le 2 est à la 2ème place, le 3 est à la première place, le 4 est à la place 0 (tout au début) (sur python c'est 0 1 2 3 donc 4 est à la place 0)

(array([2, 3, 4]), array([2, 1, 1, 0]))

In [6]:
uniq, idx = np.unique([4,3,3,2], return_index=True) # quand regarde ordre 4,3,3,2 on voit que 4 est vu en 0, 3 est vu en 1, et 2 en 3 car python (1er chiffre est 0, (0,1,2,3))
uniq, idx 

(array([2, 3, 4]), array([3, 1, 0]))

In [7]:
qf = [401, 301, 301, 201]
qf

[401, 301, 301, 201]

In [8]:
qf_attendus = [201, 301, 401]
qf_attendus

[201, 301, 401]

In [9]:
idx

array([3, 1, 0])

In [11]:
qfs = [qf[i] for i in idx]

In [12]:
uniq

array([2, 3, 4])

In [13]:
qfs 

[201, 301, 401]